# Generated by Django 5.1.7 on 2025-03-14 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='media/medication_images')),
                ('frequency', models.PositiveSmallIntegerField(help_text='How often to take it (e.g., every 8 hours)')),
                ('frequency_time_interval', models.CharField(choices=[('DAY', 'Daily'), ('HOUR', 'Hourly'), ('WEEK', 'Weekly'), ('BI-WEEK', 'Bi-weekly')], default='DAY', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(help_text='Time of day when the reminder should go off')),
                ('repeat_interval', models.PositiveSmallIntegerField(default=1, help_text='Repeat every X hours/days (e.g., every 2 hours)')),
                ('repeat_days', models.JSONField(blank=True, help_text="Specific days to repeat (e.g., ['Monday', 'Wednesday'])", null=True)),
                ('specific_date', models.DateField(blank=True, help_text='If for a specific date only', null=True)),
                ('active', models.BooleanField(default=True, help_text='Enable or disable the reminder')),
                ('snooze_duration', models.PositiveSmallIntegerField(default=10, help_text='Snooze in minutes (e.g., 10 min snooze)')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='core.medication')),
            ],
        ),
    ]
