# Generated by Django 5.1.7 on 2025-03-14 00:21

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Untitled', max_length=255, null=True)),
                ('red_val', models.IntegerField(validators=[core.models.validate_color_range])),
                ('green_val', models.IntegerField(validators=[core.models.validate_color_range])),
                ('blue_val', models.IntegerField(validators=[core.models.validate_color_range])),
            ],
        ),
    ]
