# Generated by Django 5.1.7 on 2025-03-14 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='color',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.color'),
        ),
    ]
