# Generated by Django 5.1.7 on 2025-03-14 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_medication_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='ends_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
