# Generated by Django 5.1.7 on 2025-03-14 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_reminder_ends_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='dosage',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='medication',
            name='unit',
            field=models.CharField(default='_', help_text='How much do you take per dose? (e.g. pill, teaspoon, etc)', max_length=255),
        ),
    ]
